### ISSUE TITLE
Find out where all off target reads are in PKD

### ISSUE THREAD

**Issue by mattdmem** [sch-sdgs/SDGSPipeline#49]
there are lots of off-target reads in iontorrent panels - it would be interesting to see where these come from

**Comment by lsollars** [comment]
Calculation doesn't take into account the long-range design of PKD test. It looks like there are loads of off-target reads in PKD because they map to the whole of the 8 long-range fragments, whereas the calculation of off-target reads only takes into account the BED file regions (exons +/- 25bp). Therefore most reads are on target (in the fragments) but outside the BED regions.
